### ISSUE TITLE
startUpdate won't send playState

### ISSUE THREAD

**Issue by mcartagenah** [2bbb/node-abletonlink#13]
According to the documentation, the startUpdate method has a callback which returns beat, phase, bpm and playState.

I'm receiving undefined if I ask for the playState.

**Comment by 2bbb** [comment]
@mcartagenah 

thanks for issue.

but, now I'm busy...
i will check it when I get free.

**Comment by 2bbb** [comment]
@mcartagenah 

sorry for my sooooooo late response...

maybe, this problem was solved by #15 by @tbazin !!

please check it!

**Comment by 2bbb** [comment]
if something wrong, please reopen.

**Comment by ktamas77** [comment]
This issue still exists -> update won't update playState, its always `undefined`.
`link.on('playState')` also never will be triggered.
However, `link.onPlayStateChanged()` works, but sadly it's not super useful as we don't know the initial state.

**Comment by ktamas77** [comment]
Reopened in #18
